version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: onion-farm_web_1
      APP_PORT: 5000
      PROXY_AUTH_ADD: "false"
  
  web:
    image: ricardobchaves6/onion-farm:v1.0.0
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${APP_DATA_DIR}/html/:/var/www/html/
      - ${APP_DATA_DIR}/http.d/:/etc/nginx/http.d/
      - ${APP_DATA_DIR}/torrc.d/:/etc/torrc.d/
      - ${APP_DATA_DIR}/tor/:/var/lib/tor/
